version: '3.8'

services:
  ffc-sfi-agreement:
    build:
      context: .
      target: production
    image: ffc-sfi-agreement
    container_name: ffc-sfi-agreement
    depends_on:
      - ffc-sfi-agreement-postgres
    environment:
      AGREEMENT_CHANGED_TOPIC_ADDRESS: ${AGREEMENT_CHANGED_TOPIC_ADDRESS:-notset}
      ELIGIBILITY_CHANGED_TOPIC_ADDRESS: ${ELIGIBILITY_CHANGED_TOPIC_ADDRESS:-notset}
      POSTGRES_DB: ffc_sfi_agreement
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: postgres
      POSTGRES_HOST: ffc-sfi-agreement-postgres
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: public
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      UPDATE_AGREEMENT_QUEUE_ADDRESS: ${UPDATE_AGREEMENT_QUEUE_ADDRESS:-notset}
      UPDATE_ELIGIBILITY_QUEUE_ADDRESS: ${UPDATE_ELIGIBILITY_QUEUE_ADDRESS:-notset}

  ffc-sfi-agreement-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_agreement
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
