version: '3.8'

services:
  ffc-sfi-agreement:
    build:
      context: .
      target: production
    image: ffc-sfi-agreement
    container_name: ffc-sfi-agreement
    environment:
      AGREEMENT_CHANGED_TOPIC_ADDRESS: ${AGREEMENT_CHANGED_TOPIC_ADDRESS:-notset
      ELIGIBILITY_CHANGED_TOPIC_ADDRESS: ${ELIGIBILITY_CHANGED_TOPIC_ADDRESS:-notset
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      UPDATE_AGREEMENT_QUEUE_ADDRESS: ${UPDATE_AGREEMENT_QUEUE_ADDRESS:-notset}
      UPDATE_ELIGIBILIY_QUEUE_ADDRESS: ${UPDATE_ELIGIBILIY_QUEUE_ADDRESS:-notset}
