environment: development
name: ffc-sfi-agreement
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-agreement

labels: {}

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-agreement-config-map

containerSecret:
  name: ffc-sfi-agreement-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  messageQueueHost: dummy
  updateAgreementQueueAddress: update-agreement
  agreementChangedTopicAddress: agreement-changed
  updateEligibilityQueueAddress: update-eligibility
  eligibilityChangedTopicAddress: eligibility-changed

postgresService:
  postgresDb: ffc_sfi_agreement
  postgresExternalName:
  postgresHost: ffc-sfi-agreement-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
